"""
Django settings for DJANGO_ADMIN_KEYCLOAK project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent


ALLOWED_HOSTS = []


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'mozilla_django_oidc',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'mozilla_django_oidc.middleware.SessionRefresh',
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'authentication.KeycloakOIDCBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


ROOT_URLCONF = "DJANGO_ADMIN_KEYCLOAK.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


ID_BASE_URL = os.getenv('ID_BASE_URL')
OIDC_RP_CLIENT_ID = os.getenv('OIDC_RP_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET')
OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_OP_AUTHORIZATION_ENDPOINT')
LOGOUT_REDIRECT_URL = os.getenv('LOGOUT_REDIRECT_URL')
OIDC_REALM = os.getenv('OIDC_REALM')
OIDC_LOGIN = os.getenv('OIDC_LOGIN', True)

SOCIALACCOUNT_PROVIDERS = {
    'openid_connect': {
        'KEY': OIDC_RP_CLIENT_ID,
        'SECRET': OIDC_RP_CLIENT_SECRET,
        'AUTH_PARAMS': {'response_type': 'code'},
        'SCOPE': ['openid', 'profile', 'email'],
        'OAUTH2_URL': {
            'authorization_url': f'https://{ID_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/auth',
            'access_token_url': f'https://{ID_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/token',
            'profile_url': f'https://{ID_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/userinfo',
        },
        'USER_INFO': {
            'endpoint': f'https://{ID_BASE_URL}/realms/{OIDC_REALM}/protocol/openid-connect/userinfo',
            'claims': ['sub', 'email', 'preferred_username', 'given_name', 'family_name']
        }
    }
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
